docs: :memo: decision post on why to use the Frictionless Data standard
seedcase-project/decisions pull request #100
Opened 2024-07-15 18:03 UTC by lwjohnst86

## Description

This decision post describes why we should use the Frictionless Data standard for structuring and extracting metadata from data files.

Closes #485

## Reviewer Focus

This PR needs a bit of an in-depth review. 

## Checklist

- [x] Ran spell-check
- [x] Formatted Markdown
- [x] Rendered website locally

2024-07-16 09:32 UTC, martonvago requested changes
Looks like this is a great fit! 😁

2024-07-16 09:32 UTC, martonvago commented on why-frictionless-data/index.qmd
> +    data files and to create
Looks like the end of the sentence is missing

2024-07-16 09:32 UTC, martonvago commented on why-frictionless-data/index.qmd
> +and principles.
```suggestion
and this standard is owned and developed by the non-profit Open 
Knowledge Foundation, who do work in other areas that also align 
with our values and principles.
```
Something like this maybe?

2024-07-16 09:32 UTC, martonvago commented on why-frictionless-data/index.qmd
> +[Frictionless Data](https://frictionlessdata.io/) and it's companion
```suggestion
[Frictionless Data](https://frictionlessdata.io/) and its companion
```

2024-07-17 10:06 UTC, lwjohnst86 commented on why-frictionless-data/index.qmd
> +opposite reasons we didn't consider the tools they list).
```suggestion
surprisingly wasn't listed in the resources above. This is likely for the
opposite reasons we didn't consider the tools they list.
```

2024-07-17 10:06 UTC, lwjohnst86 commented on why-frictionless-data/index.qmd
> +    data files and to create
```suggestion
    data files and to validate the input data against the metadata.
```

2024-07-17 10:10 UTC, merged