docs: :memo: decision post on why to use pytest
seedcase-project/decisions pull request #102
Opened 2024-07-17 14:32 UTC by lwjohnst86

## Description

Add decision post on why to switch to pytest. 

Closes #101, see also seedcase-project/seedcase-sprout#226

## Reviewer Focus

This PR needs a bit of a review. 

## Checklist

- [x] Ran spell-check
- [x] Formatted Markdown
- [x] Rendered website locally

2024-07-24 14:48 UTC, martonvago requested changes
👍 👍 👍

2024-07-24 14:48 UTC, martonvago commented on why-pytest/index.qmd
> +testing](https://en.wikipedia.org/wiki/Software_testing) that include
```suggestion
testing](https://en.wikipedia.org/wiki/Software_testing), including
```

2024-07-24 14:48 UTC, martonvago commented on why-pytest/index.qmd
> +testing](https://en.wikipedia.org/wiki/Software_testing) that include
For me the original is a bit misleading somehow.

2024-07-24 14:48 UTC, martonvago commented on why-pytest/index.qmd
> +-   Requires more extra code to setup and structure tests. For instance,
```suggestion
-   Requires more extra code to set up and structure tests. For instance,
```

2024-07-24 14:48 UTC, martonvago commented on why-pytest/index.qmd
> +-   Writing tests follows more of the object-oriented programming style,
```suggestion
-   Writing tests follows more of an object-oriented programming style,
```

2024-07-24 14:48 UTC, martonvago commented on why-pytest/index.qmd
> +-   Writing tests follows more of the object-oriented programming style,
For me at least.

2024-07-24 14:48 UTC, martonvago commented on why-pytest/index.qmd
> +    testing frameworks.
I guess it's not 100% obvious to me what this means 😅 . I would understand "other unit testing frameworks"

2024-07-29 14:17 UTC, signekb reviewed
Very nice! I have some suggestions 🚀

2024-07-29 14:17 UTC, signekb commented on why-pytest/index.qmd
> +use a Test-Driven Development workflow, we need a testing framework when
```suggestion
use a test-driven development workflow, we need a testing framework when
```
Right?

2024-07-29 14:17 UTC, signekb commented on why-pytest/index.qmd
> +worse.
```suggestion
framework in Java) and has a similar structure to it.
```

2024-07-29 14:17 UTC, signekb commented on why-pytest/index.qmd
> +-   Creating tests takes more effort and time.
more effort and time as compared to *what*? :)

2024-07-29 16:27 UTC, lwjohnst86 commented on why-pytest/index.qmd
> +-   Creating tests takes more effort and time.
```suggestion
-   Creating tests takes more effort and time compared to alternatives.
```

2024-07-29 16:27 UTC, lwjohnst86 commented on why-pytest/index.qmd
> +    which can be harder to reason about and design tests for.
This is what I've read about across multiple sources, the OOP in general is harder to test and that writing things following an OOP style is itself harder to design. E.g. https://softwareengineering.stackexchange.com/questions/351815/why-is-unit-testing-harder-in-object-oriented-programming-compared-to-functional and https://www.geeksforgeeks.org/why-is-unit-testing-harder-in-oop/

2024-07-29 16:27 UTC, lwjohnst86 commented on why-pytest/index.qmd
> +    which can be harder to reason about and design tests for.
```suggestion
    which can be harder to reason about and design tests for 
    (for multiple, highly technical reasons outside the scope of
    this post)
```

2024-07-29 16:27 UTC, lwjohnst86 commented on why-pytest/index.qmd
> +    designed than unittest.
```suggestion
    designed than unittest for Python (since unittest was modeled off of Java's framework).
```

2024-07-29 16:27 UTC, lwjohnst86 commented on why-pytest/index.qmd
> +    testing frameworks.
```suggestion
-   Integrating pytest with other types of testing frameworks can be
		a bit difficult and may require some configuration.
```

2024-08-05 14:43 UTC, merged

2024-08-06 07:20 UTC, signekb commented on why-pytest/index.qmd
> +    which can be harder to reason about and design tests for.
Great, thanks!