docs: :memo: add why post for using quartodocs
seedcase-project/decisions pull request #121
Opened 2024-10-24 19:51 UTC by lwjohnst86

## Description

This is a decision post for using quartodocs to build the Python code docstrings into a website format.

Closes #2

This PR needs an in-depth review.

## Checklist

- [x] Ran spell-check
- [x] Formatted Markdown
- [x] Rendered website locally

2024-10-25 11:27 UTC, martonvago requested changes
🎉 🎉 🎉

2024-10-25 11:27 UTC, martonvago commented on why-quartodocs/index.qmd
> +documentation into websites but that we don't consider because they
```suggestion
documentation into websites, which we don't consider because they
```

2024-10-25 11:27 UTC, martonvago commented on why-quartodocs/index.qmd
> +    full static website generators that includes a docstring-to-HTML
```suggestion
    full static website generators that include a docstring-to-HTML
```

2024-10-28 09:08 UTC, K-Beicher approved these changes, later dismissed
Looks good.

2024-10-28 14:18 UTC, merged