docs: :memo: decision post for versioning with Commitizen
seedcase-project/decisions pull request #136
Opened 2024-11-08 14:56 UTC by lwjohnst86

## Description

Closes #107

## Reviewer Focus

This PR needs a fairly short review.

## Checklist

- [x] Ran spell-check
- [x] Formatted Markdown
- [ ] Rendered website locally

2024-11-08 15:38 UTC, martonvago requested changes
Very nice!!

2024-11-08 15:38 UTC, martonvago commented on why-semantic-release-with-commitizen/index.qmd
> +a version or not is time- and energy-consuming. So instead, we would
```suggestion
a version is time- and energy-consuming. So instead, we would
```
Or change "when" to "whether"?

2024-11-08 15:38 UTC, martonvago commented on why-semantic-release-with-commitizen/index.qmd
> +    least. For instance, there isn't any tutorials or "getting started"
```suggestion
    least. For instance, there aren't any tutorials or "getting started"
```

2024-11-11 08:54 UTC, K-Beicher approved these changes
Looks good to me

2024-11-11 13:08 UTC, merged