docs: :memo: add why conventioanl branches post
seedcase-project/decisions pull request #62
Opened 2024-05-21 13:57 UTC by signekb

## Description

- This PR adds a post on the naming scheme for branches.
- Since I couldn't find specific, different conventions I chose to go into details on what to include/exclude in a branch name. 

## Related Issues

Closes seedcase-project/team#91

## Checklist

For general documentation:

- [X] Spell-check
- [X] Did the page(s) preview correctly on your machine without breaking
- [ ] New category words (keywords) (if any) added to the code snippet file

2024-05-27 14:57 UTC, lwjohnst86 requested changes
Nice! Only additional minor comment is, were there any external links you used that could be included here for reference?

2024-05-27 14:57 UTC, lwjohnst86 commented on why-conventional-branches.qmd
> +For the Seedcase project, we aim to follow best practices and have
```suggestion
For the Seedcase Project, we aim to follow best practices and have
```

2024-05-27 14:57 UTC, lwjohnst86 commented on why-conventional-branches.qmd
> +2.  Only use alphanumeric characters (avoid punctuation, spaces,
```suggestion
2.  Only use alphanumeric characters (don't use punctuation, spaces,
```

2024-05-27 14:57 UTC, lwjohnst86 commented on why-conventional-branches.qmd
> +of this practice:
```suggestion
track of each developer's work.
```

2024-05-27 17:36 UTC, signekb commented
> Nice! Only additional minor comment is, were there any external links you used that could be included here for reference?

Definitely! I'll see if I can find them again 🌴

2024-05-29 07:30 UTC, K-Beicher approved these changes, later dismissed
This is very helpful

2024-06-08 10:50 UTC, lwjohnst86 approved these changes
⭐

2024-06-08 10:50 UTC, merged