docs: make references to Seedcase software/products more uniform
seedcase-project/decisions pull request #72
Opened 2024-06-04 12:30 UTC by martonvago

## Description

This PR attempts to make references to Seedcase more uniform. I've tried to stick to the following guidelines:
- "the Seedcase Project": always capital S and P; use to refer to the project as a whole (including underpinning ideas)
- Bare use of "Seedcase": only allow when it refers to the project as a whole in very general terms
- "Seedcase products" / "Seedcase software" / "Seedcase software products": use to refer to the software deliverables of the project; choose best fit based on context
- "the Seedcase framework": use to refer to the collection of software deliverables that work together to implement the core functionalities; use in older documentation to shift the meaning away from a single product without rewriting large chunks of text that will probably change significantly anyway
- "Data Resource": always capital D and R; use to refer to the data layer in the framework and its contents

I've also formatted the files I touched, so there are some whitespace changes.

In general, these changes are pretty subjective and can be controversial, so feel free to be critical.

## Related Issues: https://github.com/seedcase-project/design/issues/21

## Testing

- [ ] Yes
- [x] No, not needed (give a reason below)
- [ ] No, I need help writing them

Tested in the browser.

## Reviewer Focus

This PR only needs a quick review.

## Checklist

For general documentation:

- [x] Spell-check
    - [ ] US
    - [ ] UK
- [x] Did the page(s) preview correctly on your machine without breaking
- [x] New category words (keywords) (if any) added to the code snippet file

2024-06-04 12:32 UTC, martonvago commented on why-conventional-commits.qmd
> +description: "Our reasons for using conventional commits (with optional emojis following the Gitmoji convention) across Seedcase codebases."
Here and below just trying to avoid using "projects" when we have "the Seedcase Project" as an overarching category.

2024-06-06 07:49 UTC, lwjohnst86 commented on why-conventional-commits.qmd
> +description: "Our reasons for using conventional commits (with optional emojis following the Gitmoji convention) across Seedcase codebases."
```suggestion
description: "Our reasons for using conventional commits (with optional emojis following the Gitmoji convention) across Seedcase repositories."
```

2024-06-06 07:56 UTC, lwjohnst86 requested changes
A small change.

2024-06-06 07:56 UTC, lwjohnst86 commented on why-conventional-commits.qmd
> +description: "Our reasons for using conventional commits (with optional emojis following the Gitmoji convention) across Seedcase codebases."
Great idea! Let's be clearer and mean the git repositories ☺️

2024-06-07 08:47 UTC, lwjohnst86 approved these changes

2024-06-07 08:47 UTC, merged